from __future__ import annotations

from typing import Any


TABLE_FIELD_MAPPING: dict[str, Any] = {
    "mapping_types": {
        "data_property": "字段对应本体类的数据属性，例如编码、名称、数量、日期、成本。",
        "object_property": "字段对应本体对象关系，例如 BOM 指向整车、运输通道指向起点节点。",
        "class_discriminator": "字段用于区分抽象类下的子类，例如节点类型区分工厂、供应商、仓库、客户。",
    },
    "mappings": [
        {
            "table_name": "product",
            "table_label": "产品表",
            "ontology_class": "Product",
            "ontology_domain": "Product Domain",
            "description": "所有物料对象的抽象父类实例。",
            "fields": [
                {"field_name": "product_id", "ontology_target": "Product.productId", "mapping_type": "data_property"},
                {"field_name": "product_name", "ontology_target": "Product.productName", "mapping_type": "data_property"},
                {"field_name": "product_type", "ontology_target": "Vehicle / Module / Component / RawMaterial", "mapping_type": "class_discriminator"},
                {"field_name": "uom", "ontology_target": "Product.unitOfMeasure", "mapping_type": "data_property"},
                {"field_name": "unit_cost", "ontology_target": "Product.unitCost", "mapping_type": "data_property"},
                {"field_name": "lifecycle_stage", "ontology_target": "Product.lifeCycleStage", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "vehicle",
            "table_label": "整车表",
            "ontology_class": "Vehicle",
            "ontology_domain": "Product Domain",
            "description": "整车 SKU 实例，是需求链的核心对象。",
            "fields": [
                {"field_name": "vehicle_id", "ontology_target": "Vehicle.productId", "mapping_type": "data_property"},
                {"field_name": "product_id", "ontology_target": "Vehicle subclassOf Product", "mapping_type": "object_property"},
                {"field_name": "vehicle_code", "ontology_target": "Vehicle.productName / code", "mapping_type": "data_property"},
                {"field_name": "vehicle_family", "ontology_target": "Vehicle.vehicleSeries", "mapping_type": "data_property"},
                {"field_name": "energy_type", "ontology_target": "Vehicle.energyType", "mapping_type": "data_property"},
                {"field_name": "trim_level", "ontology_target": "Vehicle.trimLevel", "mapping_type": "data_property"},
                {"field_name": "launch_date", "ontology_target": "Vehicle.launchDate", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "module",
            "table_label": "核心模块表",
            "ontology_class": "Module",
            "ontology_domain": "Product Domain",
            "description": "电池包、电驱、底盘等关键模块实例。",
            "fields": [
                {"field_name": "module_id", "ontology_target": "Module.productId", "mapping_type": "data_property"},
                {"field_name": "module_code", "ontology_target": "Module.productName / code", "mapping_type": "data_property"},
                {"field_name": "module_name", "ontology_target": "Module.productName", "mapping_type": "data_property"},
                {"field_name": "module_family", "ontology_target": "Module.moduleType", "mapping_type": "data_property"},
                {"field_name": "criticality", "ontology_target": "Module.criticality", "mapping_type": "data_property"},
                {"field_name": "uom", "ontology_target": "Product.unitOfMeasure", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "configuration_option",
            "table_label": "配置选项表",
            "ontology_class": "ConfigurationOption",
            "ontology_domain": "Product Domain",
            "description": "车型下的可选配置维度实例。",
            "fields": [
                {"field_name": "option_id", "ontology_target": "ConfigurationOption.configId", "mapping_type": "data_property"},
                {"field_name": "option_code", "ontology_target": "ConfigurationOption.configName / code", "mapping_type": "data_property"},
                {"field_name": "option_name", "ontology_target": "ConfigurationOption.configName", "mapping_type": "data_property"},
                {"field_name": "option_category", "ontology_target": "ConfigurationOption.configCategory", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "alternate_material_group",
            "table_label": "替代料组表",
            "ontology_class": "AlternateMaterialGroup",
            "ontology_domain": "Product Domain",
            "description": "可互换物料的逻辑分组。",
            "fields": [
                {"field_name": "alt_group_id", "ontology_target": "AlternateMaterialGroup.groupId", "mapping_type": "data_property"},
                {"field_name": "group_name", "ontology_target": "AlternateMaterialGroup.groupName", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "region",
            "table_label": "区域表",
            "ontology_class": "Region",
            "ontology_domain": "Network Domain",
            "description": "供应链节点所属的国家、大区或服务区域。",
            "fields": [
                {"field_name": "region_id", "ontology_target": "Region.regionId", "mapping_type": "data_property"},
                {"field_name": "region_name", "ontology_target": "Region.regionName", "mapping_type": "data_property"},
                {"field_name": "country", "ontology_target": "Region.country", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "supply_chain_node",
            "table_label": "供应链节点表",
            "ontology_class": "SupplyChainNode / Plant / SupplierSite / Warehouse / CustomerNode",
            "ontology_domain": "Network Domain",
            "description": "供应商、工厂、仓库、客户等物理节点。",
            "fields": [
                {"field_name": "node_id", "ontology_target": "SupplyChainNode.nodeId", "mapping_type": "data_property"},
                {"field_name": "node_code", "ontology_target": "SupplyChainNode.nodeCode", "mapping_type": "data_property"},
                {"field_name": "node_name", "ontology_target": "SupplyChainNode.nodeName", "mapping_type": "data_property"},
                {"field_name": "node_type", "ontology_target": "Plant / SupplierSite / Warehouse / CustomerNode", "mapping_type": "class_discriminator"},
                {"field_name": "region_id", "ontology_target": "locatedIn -> Region", "mapping_type": "object_property"},
                {"field_name": "is_manufacturing", "ontology_target": "Plant marker", "mapping_type": "class_discriminator"},
                {"field_name": "is_supplier", "ontology_target": "SupplierSite marker", "mapping_type": "class_discriminator"},
                {"field_name": "is_distribution", "ontology_target": "Warehouse marker", "mapping_type": "class_discriminator"},
                {"field_name": "is_customer", "ontology_target": "CustomerNode marker", "mapping_type": "class_discriminator"},
            ],
        },
        {
            "table_name": "transportation_lane",
            "table_label": "运输通道表",
            "ontology_class": "TransportationLane",
            "ontology_domain": "Network Domain",
            "description": "两个供应链节点之间的物流路径。",
            "fields": [
                {"field_name": "lane_id", "ontology_target": "TransportationLane.laneId", "mapping_type": "data_property"},
                {"field_name": "from_node_id", "ontology_target": "originNode -> SupplyChainNode", "mapping_type": "object_property"},
                {"field_name": "to_node_id", "ontology_target": "destinationNode -> SupplyChainNode", "mapping_type": "object_property"},
                {"field_name": "transport_mode", "ontology_target": "TransportationLane.transportMode", "mapping_type": "data_property"},
                {"field_name": "lead_time_days", "ontology_target": "TransportationLane.leadTime", "mapping_type": "data_property"},
                {"field_name": "distance_km", "ontology_target": "TransportationLane.distance", "mapping_type": "data_property"},
                {"field_name": "capacity_per_day", "ontology_target": "TransportationLane.capacity", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "production_line",
            "table_label": "产线表",
            "ontology_class": "ProductionLine",
            "ontology_domain": "Manufacturing Domain",
            "description": "工厂内的制造资源。",
            "fields": [
                {"field_name": "production_line_id", "ontology_target": "ProductionLine.lineId", "mapping_type": "data_property"},
                {"field_name": "line_code", "ontology_target": "ProductionLine.lineCode", "mapping_type": "data_property"},
                {"field_name": "line_name", "ontology_target": "ProductionLine.lineName", "mapping_type": "data_property"},
                {"field_name": "plant_node_id", "ontology_target": "locatedAt -> Plant", "mapping_type": "object_property"},
                {"field_name": "line_type", "ontology_target": "ProductionLine.resourceType", "mapping_type": "data_property"},
                {"field_name": "status", "ontology_target": "ProductionLine.status", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "production_capability",
            "table_label": "生产能力表",
            "ontology_class": "ProductionCapability",
            "ontology_domain": "Manufacturing Domain",
            "description": "某产线生产某产品的能力参数。",
            "fields": [
                {"field_name": "production_capability_id", "ontology_target": "ProductionCapability.capabilityId", "mapping_type": "data_property"},
                {"field_name": "production_line_id", "ontology_target": "capabilityDefinedForLine -> ProductionLine", "mapping_type": "object_property"},
                {"field_name": "target_object_type", "ontology_target": "Vehicle / Module", "mapping_type": "class_discriminator"},
                {"field_name": "target_object_id", "ontology_target": "canProduceProduct -> Product", "mapping_type": "object_property"},
                {"field_name": "daily_capacity", "ontology_target": "ProductionCapability.capacity", "mapping_type": "data_property"},
                {"field_name": "changeover_minutes", "ontology_target": "ProductionCapability.changeoverTime", "mapping_type": "data_property"},
                {"field_name": "yield_rate", "ontology_target": "ProductionCapability.yieldRate", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "work_calendar",
            "table_label": "工作日历表",
            "ontology_class": "WorkCalendar",
            "ontology_domain": "Manufacturing Domain",
            "description": "生产、运输或收发货日历模板。",
            "fields": [
                {"field_name": "work_calendar_id", "ontology_target": "WorkCalendar.calendarId", "mapping_type": "data_property"},
                {"field_name": "production_line_id", "ontology_target": "calendarForLine -> ProductionLine", "mapping_type": "object_property"},
                {"field_name": "calendar_type", "ontology_target": "WorkCalendar.calendarType", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "daily_work_schedule",
            "table_label": "日工作安排表",
            "ontology_class": "DailyWorkSchedule",
            "ontology_domain": "Manufacturing Domain",
            "description": "工作日历下的每日班次与可用工时。",
            "fields": [
                {"field_name": "daily_schedule_id", "ontology_target": "DailyWorkSchedule.scheduleId", "mapping_type": "data_property"},
                {"field_name": "work_calendar_id", "ontology_target": "belongsToCalendar -> WorkCalendar", "mapping_type": "object_property"},
                {"field_name": "weekday", "ontology_target": "DailyWorkSchedule.weekday", "mapping_type": "data_property"},
                {"field_name": "shift_count", "ontology_target": "DailyWorkSchedule.shiftCount", "mapping_type": "data_property"},
                {"field_name": "available_hours", "ontology_target": "DailyWorkSchedule.availableHours", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "bill_of_materials",
            "table_label": "BOM表",
            "ontology_class": "BillOfMaterials",
            "ontology_domain": "Manufacturing Domain",
            "description": "生产某整车所需的制造配方。",
            "fields": [
                {"field_name": "bom_id", "ontology_target": "BillOfMaterials.bomId", "mapping_type": "data_property"},
                {"field_name": "parent_vehicle_id", "ontology_target": "outputsProduct -> Vehicle", "mapping_type": "object_property"},
                {"field_name": "bom_version", "ontology_target": "BillOfMaterials.version", "mapping_type": "data_property"},
                {"field_name": "effective_start_date", "ontology_target": "BillOfMaterials.effectiveFrom", "mapping_type": "data_property"},
                {"field_name": "effective_end_date", "ontology_target": "BillOfMaterials.effectiveTo", "mapping_type": "data_property"},
                {"field_name": "status", "ontology_target": "BillOfMaterials.status", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "bom_line_item",
            "table_label": "BOM行项目表",
            "ontology_class": "BOMLineItem",
            "ontology_domain": "Manufacturing Domain",
            "description": "BOM 中每一条子件用量记录。",
            "fields": [
                {"field_name": "bom_line_item_id", "ontology_target": "BOMLineItem.lineItemId", "mapping_type": "data_property"},
                {"field_name": "bom_id", "ontology_target": "hasLineItem / belongsToBOM -> BillOfMaterials", "mapping_type": "object_property"},
                {"field_name": "sequence_no", "ontology_target": "BOMLineItem.sequenceNo", "mapping_type": "data_property"},
                {"field_name": "component_module_id", "ontology_target": "consumesProduct -> Module", "mapping_type": "object_property"},
                {"field_name": "quantity_per", "ontology_target": "BOMLineItem.quantityPer", "mapping_type": "data_property"},
                {"field_name": "uom", "ontology_target": "BOMLineItem.unitOfMeasure", "mapping_type": "data_property"},
                {"field_name": "configuration_option_id", "ontology_target": "conditionedByOption -> ConfigurationOption", "mapping_type": "object_property"},
                {"field_name": "alternate_material_group_id", "ontology_target": "refersToAlternateGroup -> AlternateMaterialGroup", "mapping_type": "object_property"},
            ],
        },
        {
            "table_name": "demand",
            "table_label": "需求表",
            "ontology_class": "Demand",
            "ontology_domain": "Demand Domain",
            "description": "预测需求和客户订单的抽象需求记录。",
            "fields": [
                {"field_name": "demand_id", "ontology_target": "Demand.demandId", "mapping_type": "data_property"},
                {"field_name": "demand_type", "ontology_target": "DemandForecast / CustomerOrder", "mapping_type": "class_discriminator"},
                {"field_name": "vehicle_id", "ontology_target": "demandForProduct -> Vehicle", "mapping_type": "object_property"},
                {"field_name": "node_id", "ontology_target": "demandAtNode -> SupplyChainNode", "mapping_type": "object_property"},
                {"field_name": "demand_date", "ontology_target": "Demand.demandDate", "mapping_type": "data_property"},
                {"field_name": "quantity", "ontology_target": "Demand.quantity", "mapping_type": "data_property"},
                {"field_name": "priority", "ontology_target": "Demand.priority", "mapping_type": "data_property"},
                {"field_name": "status", "ontology_target": "Demand.status", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "demand_forecast",
            "table_label": "需求预测表",
            "ontology_class": "DemandForecast",
            "ontology_domain": "Demand Domain",
            "description": "基于市场分析的预测需求。",
            "fields": [
                {"field_name": "demand_forecast_id", "ontology_target": "DemandForecast.forecastId", "mapping_type": "data_property"},
                {"field_name": "demand_id", "ontology_target": "DemandForecast subclassOf Demand", "mapping_type": "object_property"},
                {"field_name": "forecast_version", "ontology_target": "belongsToPlan -> DemandPlan", "mapping_type": "object_property"},
                {"field_name": "confidence", "ontology_target": "DemandForecast.confidence", "mapping_type": "data_property"},
                {"field_name": "forecast_bucket", "ontology_target": "DemandForecast.forecastBucket", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "customer_order",
            "table_label": "客户订单表",
            "ontology_class": "CustomerOrder",
            "ontology_domain": "Demand Domain",
            "description": "用户已下单的确认需求。",
            "fields": [
                {"field_name": "customer_order_id", "ontology_target": "CustomerOrder.orderId", "mapping_type": "data_property"},
                {"field_name": "demand_id", "ontology_target": "CustomerOrder subclassOf Demand", "mapping_type": "object_property"},
                {"field_name": "requested_delivery_date", "ontology_target": "CustomerOrder.requestedDeliveryDate", "mapping_type": "data_property"},
                {"field_name": "promised_delivery_date", "ontology_target": "CustomerOrder.promisedDeliveryDate", "mapping_type": "data_property"},
                {"field_name": "customer_segment", "ontology_target": "CustomerOrder.customerSegment", "mapping_type": "data_property"},
                {"field_name": "channel", "ontology_target": "CustomerOrder.channel", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "take_rate_profile",
            "table_label": "选装率表",
            "ontology_class": "TakeRateProfile",
            "ontology_domain": "Demand Domain",
            "description": "车辆配置选项的选择比例。",
            "fields": [
                {"field_name": "take_rate_profile_id", "ontology_target": "TakeRateProfile.profileId", "mapping_type": "data_property"},
                {"field_name": "vehicle_id", "ontology_target": "takeRateForVehicle -> Vehicle", "mapping_type": "object_property"},
                {"field_name": "option_id", "ontology_target": "takeRateForOption -> ConfigurationOption", "mapping_type": "object_property"},
                {"field_name": "take_rate", "ontology_target": "TakeRateProfile.takeRate", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "supply",
            "table_label": "供应表",
            "ontology_class": "Supply",
            "ontology_domain": "Supply Domain",
            "description": "库存、采购、在途等供应记录的抽象父类。",
            "fields": [
                {"field_name": "supply_id", "ontology_target": "Supply.supplyId", "mapping_type": "data_property"},
                {"field_name": "supply_type", "ontology_target": "OnHandInventory / PurchaseOrder / InTransitShipment", "mapping_type": "class_discriminator"},
                {"field_name": "object_type", "ontology_target": "Vehicle / Module", "mapping_type": "class_discriminator"},
                {"field_name": "object_id", "ontology_target": "suppliesProduct -> Product", "mapping_type": "object_property"},
                {"field_name": "node_id", "ontology_target": "availableAtNode -> SupplyChainNode", "mapping_type": "object_property"},
                {"field_name": "available_date", "ontology_target": "Supply.availableDate", "mapping_type": "data_property"},
                {"field_name": "quantity", "ontology_target": "Supply.quantity", "mapping_type": "data_property"},
                {"field_name": "status", "ontology_target": "Supply.status", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "on_hand_inventory",
            "table_label": "现有库存表",
            "ontology_class": "OnHandInventory",
            "ontology_domain": "Supply Domain",
            "description": "已经位于某节点、当前可用或质检中的库存。",
            "fields": [
                {"field_name": "on_hand_inventory_id", "ontology_target": "OnHandInventory.inventoryId", "mapping_type": "data_property"},
                {"field_name": "supply_id", "ontology_target": "inventoryOf -> Supply", "mapping_type": "object_property"},
                {"field_name": "lot_id", "ontology_target": "OnHandInventory.lotId", "mapping_type": "data_property"},
                {"field_name": "quality_status", "ontology_target": "OnHandInventory.qualityStatus", "mapping_type": "data_property"},
                {"field_name": "days_of_cover", "ontology_target": "OnHandInventory.daysOfCover", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "purchase_order",
            "table_label": "采购订单表",
            "ontology_class": "PurchaseOrder",
            "ontology_domain": "Supply Domain",
            "description": "供应商到工厂的采购补货记录。",
            "fields": [
                {"field_name": "purchase_order_id", "ontology_target": "PurchaseOrder.poId", "mapping_type": "data_property"},
                {"field_name": "supply_id", "ontology_target": "orderForSupply -> Supply", "mapping_type": "object_property"},
                {"field_name": "supplier_node_id", "ontology_target": "orderedFrom -> SupplierSite", "mapping_type": "object_property"},
                {"field_name": "receiving_node_id", "ontology_target": "deliveredTo -> Plant", "mapping_type": "object_property"},
                {"field_name": "order_date", "ontology_target": "PurchaseOrder.orderDate", "mapping_type": "data_property"},
                {"field_name": "promised_date", "ontology_target": "PurchaseOrder.promisedDate", "mapping_type": "data_property"},
                {"field_name": "unit_cost", "ontology_target": "PurchaseOrder.unitCost", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "in_transit_shipment",
            "table_label": "在途运输表",
            "ontology_class": "InTransitShipment",
            "ontology_domain": "Supply Domain",
            "description": "已经发运但尚未到达的供应记录。",
            "fields": [
                {"field_name": "in_transit_shipment_id", "ontology_target": "InTransitShipment.shipmentId", "mapping_type": "data_property"},
                {"field_name": "supply_id", "ontology_target": "shipmentForSupply -> Supply", "mapping_type": "object_property"},
                {"field_name": "lane_id", "ontology_target": "usesLane -> TransportationLane", "mapping_type": "object_property"},
                {"field_name": "ship_date", "ontology_target": "InTransitShipment.shipDate", "mapping_type": "data_property"},
                {"field_name": "estimated_arrival_date", "ontology_target": "InTransitShipment.etaDate", "mapping_type": "data_property"},
                {"field_name": "tracking_status", "ontology_target": "InTransitShipment.trackingStatus", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "supplier_capacity_week",
            "table_label": "供应商周产能表",
            "ontology_class": "SupplierCapacity",
            "ontology_domain": "Supply Domain",
            "description": "供应商对模块的周供货能力。",
            "fields": [
                {"field_name": "supplier_capacity_week_id", "ontology_target": "SupplierCapacity.capacityId", "mapping_type": "data_property"},
                {"field_name": "supplier_node_id", "ontology_target": "capacityDefinedForSupplier -> SupplierSite", "mapping_type": "object_property"},
                {"field_name": "module_id", "ontology_target": "capacityDefinedForProduct -> Module", "mapping_type": "object_property"},
                {"field_name": "receiving_node_id", "ontology_target": "capacityDeliveredTo -> Plant", "mapping_type": "object_property"},
                {"field_name": "week_start", "ontology_target": "SupplierCapacity.effectiveWeek", "mapping_type": "data_property"},
                {"field_name": "cap_qty", "ontology_target": "SupplierCapacity.capacity", "mapping_type": "data_property"},
                {"field_name": "procurement_lead_time_days", "ontology_target": "SupplierCapacity.leadTime", "mapping_type": "data_property"},
                {"field_name": "source_flag", "ontology_target": "SupplierCapacity.sourceFlag", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "planning_policy",
            "table_label": "计划策略表",
            "ontology_class": "PlanningPolicy",
            "ontology_domain": "Planning Domain",
            "description": "产品、地点、区域层面的计划参数集合。",
            "fields": [
                {"field_name": "planning_policy_id", "ontology_target": "PlanningPolicy.policyId", "mapping_type": "data_property"},
                {"field_name": "region_id", "ontology_target": "policyForRegion -> Region", "mapping_type": "object_property"},
                {"field_name": "service_level", "ontology_target": "PlanningPolicy.serviceLevel", "mapping_type": "data_property"},
                {"field_name": "delivery_weight", "ontology_target": "PlanningPolicy.deliveryWeight", "mapping_type": "data_property"},
                {"field_name": "resource_weight", "ontology_target": "PlanningPolicy.resourceWeight", "mapping_type": "data_property"},
                {"field_name": "cost_weight", "ontology_target": "PlanningPolicy.costWeight", "mapping_type": "data_property"},
            ],
        },
        {
            "table_name": "sourcing_policy",
            "table_label": "寻源策略表",
            "ontology_class": "SourcingPolicy",
            "ontology_domain": "Planning Domain",
            "description": "特定运输通道在特定场景或时间段的寻源比例。",
            "fields": [
                {"field_name": "sourcing_policy_id", "ontology_target": "SourcingPolicy.policyId", "mapping_type": "data_property"},
                {"field_name": "lane_id", "ontology_target": "policyForLane -> TransportationLane", "mapping_type": "object_property"},
                {"field_name": "sourcing_ratio", "ontology_target": "SourcingPolicy.sourcingRatio", "mapping_type": "data_property"},
                {"field_name": "effective_start_date", "ontology_target": "SourcingPolicy.effectiveFrom", "mapping_type": "data_property"},
                {"field_name": "effective_end_date", "ontology_target": "SourcingPolicy.effectiveTo", "mapping_type": "data_property"},
            ],
        },
    ],
}


def get_table_field_mapping() -> dict[str, Any]:
    return TABLE_FIELD_MAPPING


ONTOLOGY_CLASS_RECORD_SPECS: dict[str, dict[str, Any]] = {
    "Product": {
        "ontology_domain": "Product Domain",
        "source_table": "product",
        "description": "产品抽象类实例。当前数据主要承载整车族层面的产品记录。",
    },
    "Vehicle": {
        "ontology_domain": "Product Domain",
        "source_table": "vehicle",
        "description": "整车 SKU 实例。",
    },
    "Module": {
        "ontology_domain": "Product Domain",
        "source_table": "module",
        "description": "核心模块实例。",
    },
    "Component": {
        "ontology_domain": "Product Domain",
        "source_table": "product",
        "filters": {"product_type": "Component"},
        "description": "零部件类。本体中存在，当前仿真数据尚未生成 Component 类型记录。",
    },
    "RawMaterial": {
        "ontology_domain": "Product Domain",
        "source_table": "product",
        "filters": {"product_type": "RawMaterial"},
        "description": "原材料类。本体中存在，当前仿真数据尚未生成 RawMaterial 类型记录。",
    },
    "ConfigurationOption": {
        "ontology_domain": "Product Domain",
        "source_table": "configuration_option",
        "description": "配置选项实例。",
    },
    "AlternateMaterialGroup": {
        "ontology_domain": "Product Domain",
        "source_table": "alternate_material_group",
        "description": "替代料组实例。",
    },
    "SupplyChainNode": {
        "ontology_domain": "Network Domain",
        "source_table": "supply_chain_node",
        "description": "供应链物理节点抽象类，包含工厂、供应商节点、仓库、客户节点。",
    },
    "Plant": {
        "ontology_domain": "Network Domain",
        "source_table": "supply_chain_node",
        "filters": {"node_type": "PLANT"},
        "description": "工厂节点。由 supply_chain_node.node_type = PLANT 表示。",
    },
    "SupplierSite": {
        "ontology_domain": "Network Domain",
        "source_table": "supply_chain_node",
        "filters": {"node_type": "SUPPLIER"},
        "description": "供应商地点节点。由 supply_chain_node.node_type = SUPPLIER 表示。",
    },
    "DistributionCenter": {
        "ontology_domain": "Network Domain",
        "source_table": "supply_chain_node",
        "filters": {"node_type": "WAREHOUSE"},
        "description": "分拨中心或仓库节点。由 supply_chain_node.node_type = WAREHOUSE 表示。",
    },
    "DeliveryCenter": {
        "ontology_domain": "Network Domain",
        "source_table": "supply_chain_node",
        "filters": {"node_type": "CUSTOMER"},
        "description": "交付中心或客户节点。由 supply_chain_node.node_type = CUSTOMER 表示。",
    },
    "Region": {
        "ontology_domain": "Network Domain",
        "source_table": "region",
        "description": "区域实例。",
    },
    "TransportationLane": {
        "ontology_domain": "Network Domain",
        "source_table": "transportation_lane",
        "description": "运输通道实例。",
    },
    "ProductionLine": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "production_line",
        "description": "产线实例。",
    },
    "ProductionCapability": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "production_capability",
        "description": "产线生产产品的能力实例。",
    },
    "WorkCalendar": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "work_calendar",
        "description": "工作日历实例。",
    },
    "DailyWorkSchedule": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "daily_work_schedule",
        "description": "每日工作安排实例。",
    },
    "BillOfMaterials": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "bill_of_materials",
        "description": "BOM 实例。",
    },
    "BOMLineItem": {
        "ontology_domain": "Manufacturing Domain",
        "source_table": "bom_line_item",
        "description": "BOM 行项目实例。",
    },
    "Demand": {
        "ontology_domain": "Demand Domain",
        "source_table": "demand",
        "description": "需求抽象类实例，包含预测需求和客户订单对应的基础需求记录。",
    },
    "DemandForecast": {
        "ontology_domain": "Demand Domain",
        "source_table": "demand_forecast",
        "description": "需求预测实例。",
    },
    "CustomerOrder": {
        "ontology_domain": "Demand Domain",
        "source_table": "customer_order",
        "description": "客户订单实例。",
    },
    "TakeRateProfile": {
        "ontology_domain": "Demand Domain",
        "source_table": "take_rate_profile",
        "description": "选装率实例。周粒度派生数据见 take_rate_profile_weekly。",
    },
    "DemandPlan": {
        "ontology_domain": "Demand Domain",
        "source_table": "scenario_version",
        "description": "需求计划版本当前由 scenario_version 中的 demand_version 代理表示，尚未独立生成 demand_plan 表。",
    },
    "Supply": {
        "ontology_domain": "Supply Domain",
        "source_table": "supply",
        "description": "供应抽象类实例，包含库存、采购、在途供应。",
    },
    "OnHandInventory": {
        "ontology_domain": "Supply Domain",
        "source_table": "on_hand_inventory",
        "description": "现有库存实例。",
    },
    "PurchaseOrder": {
        "ontology_domain": "Supply Domain",
        "source_table": "purchase_order",
        "description": "采购订单实例。",
    },
    "InTransitShipment": {
        "ontology_domain": "Supply Domain",
        "source_table": "in_transit_shipment",
        "description": "在途运输实例。",
    },
    "Supplier": {
        "ontology_domain": "Supply Domain",
        "source_table": "supply_chain_node",
        "filters": {"node_type": "SUPPLIER"},
        "description": "供应商实体当前由供应商节点近似表示，尚未独立生成 supplier 表。",
    },
    "SupplierCapacity": {
        "ontology_domain": "Supply Domain",
        "source_table": "supplier_capacity_week",
        "description": "供应商周产能实例。",
    },
    "PlanningPolicy": {
        "ontology_domain": "Planning Domain",
        "source_table": "planning_policy",
        "description": "计划策略实例。",
    },
    "SourcingPolicy": {
        "ontology_domain": "Planning Domain",
        "source_table": None,
        "description": "寻源策略本体类当前尚未实例化，当前仿真器没有生成 sourcing_policy 表。",
    },
}


def get_ontology_class_record_specs() -> dict[str, dict[str, Any]]:
    return ONTOLOGY_CLASS_RECORD_SPECS
